# Generated by Django 4.0.1 on 2022-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('A_id', models.IntegerField()),
                ('A_name', models.CharField(max_length=100)),
            ],
        ),
    ]
