# Generated by Django 4.0.1 on 2022-01-18 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_airline_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_arrival_time', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 40, 49, 958317))),
                ('f_departing_time', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 40, 49, 958317))),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.airline_company')),
            ],
        ),
    ]
