# Generated by Django 4.0.1 on 2022-01-18 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0003_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='f_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 43, 5, 7514)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_departing_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 43, 5, 7514)),
        ),
        migrations.CreateModel(
            name='employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.IntegerField(default=None, unique=True)),
                ('E_name', models.CharField(default=None, max_length=30)),
                ('E_password', models.CharField(default=None, max_length=15)),
                ('E_c_password', models.CharField(default=None, max_length=15)),
                ('E_pno', models.IntegerField(default=0)),
                ('E_address', models.TextField(default=None)),
                ('E_salary', models.FloatField(default=0.0)),
                ('E_designation', models.CharField(default=None, max_length=25)),
                ('E_department', models.CharField(default='undefined', max_length=100)),
                ('E_age', models.IntegerField(default=0)),
                ('E_gender', models.CharField(default='Male', max_length=5)),
                ('E_email', models.EmailField(default=None, max_length=30)),
                ('user_type', models.CharField(default='emp', max_length=50)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
