# Generated by Django 4.0.1 on 2022-01-18 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_employee1_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='f_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 44, 22, 999128)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_departing_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 44, 22, 999128)),
        ),
    ]
