# Generated by Django 4.0.1 on 2022-01-18 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_flight_f_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='f_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 49, 31, 227069)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_departing_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 49, 31, 227069)),
        ),
        migrations.CreateModel(
            name='immigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=50)),
                ('E_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
                ('P_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.passenger')),
            ],
        ),
    ]
