# Generated by Django 4.0.1 on 2022-01-18 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_flight_f_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='f_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 50, 50, 475515)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_departing_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 50, 50, 475515)),
        ),
        migrations.CreateModel(
            name='runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_id', models.CharField(max_length=5, unique=True)),
                ('status_of_terminal', models.CharField(max_length=15)),
                ('lock_time', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 50, 50, 476523))),
                ('release_time', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 50, 50, 476523))),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.airline_company')),
            ],
        ),
    ]
