# Generated by Django 4.0.1 on 2022-01-18 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_flight_f_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.IntegerField()),
                ('S_equipment', models.CharField(max_length=25)),
                ('S_price', models.FloatField()),
                ('S_quantity', models.IntegerField()),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 52, 9, 880219)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_departing_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 52, 9, 880219)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 52, 9, 881221)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 52, 9, 881221)),
        ),
    ]
