# Generated by Django 4.0.1 on 2022-02-06 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_alter_airline_company_flight_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='f_arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='f_departing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 56, 15, 186933)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 56, 15, 186933)),
        ),
    ]
