# Generated by Django 4.0.1 on 2022-02-18 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_alter_flight_f_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='flight_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.airline_company'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 12, 58, 16, 870087)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 12, 58, 16, 870087)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='status_of_terminal',
            field=models.CharField(default='not occupied', max_length=15),
        ),
    ]
