# Generated by Django 4.0.1 on 2022-02-28 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_alter_runway_flight_id_alter_runway_lock_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runway',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 23, 40, 745600)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 23, 40, 745600)),
        ),
    ]
