# Generated by Django 4.0.1 on 2022-02-28 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_runway_date_alter_runway_lock_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 55, 2, 422056)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 55, 2, 422056)),
        ),
    ]
