# Generated by Django 4.0.1 on 2022-02-28 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_runway_lock_time_alter_runway_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='f_from',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='f_status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='f_to',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 28, 14, 35, 35, 879748)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 28, 14, 35, 35, 879748)),
        ),
    ]
