# Generated by Django 4.0.1 on 2022-02-28 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_flight_f_from_flight_f_status_flight_f_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='f_arrival_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='f_departing_time',
        ),
        migrations.AddField(
            model_name='flight',
            name='f_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='flight',
            name='f_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 28, 15, 0, 59, 268083)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 28, 15, 0, 59, 268083)),
        ),
    ]
