# Generated by Django 4.0.1 on 2022-03-01 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_alter_runway_lock_time_alter_runway_release_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='R_id',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 1, 12, 3, 57, 679665)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 1, 12, 3, 57, 679665)),
        ),
    ]
