# Generated by Django 4.0.1 on 2022-03-05 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_alter_runway_r_id_alter_runway_lock_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 1, 20, 447125)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 1, 20, 447125)),
        ),
        migrations.CreateModel(
            name='runway1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_id', models.CharField(default=None, max_length=5)),
                ('status_of_terminal', models.CharField(default='not occupied', max_length=15)),
                ('date', models.DateField(default=None)),
                ('lock_time', models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 1, 20, 448124))),
                ('release_time', models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 1, 20, 448124))),
                ('flight_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.airline_company')),
            ],
        ),
    ]
