# Generated by Django 4.0.1 on 2022-03-05 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_alter_runway_lock_time_alter_runway_release_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 472959)),
        ),
        migrations.AlterField(
            model_name='runway',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 472959)),
        ),
        migrations.AlterField(
            model_name='runway1',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 473966)),
        ),
        migrations.AlterField(
            model_name='runway1',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 473966)),
        ),
        migrations.AlterField(
            model_name='runway2',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 474965)),
        ),
        migrations.AlterField(
            model_name='runway2',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 474965)),
        ),
        migrations.AlterField(
            model_name='runway3',
            name='lock_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 474965)),
        ),
        migrations.AlterField(
            model_name='runway3',
            name='release_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 474965)),
        ),
        migrations.CreateModel(
            name='runway4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_id', models.CharField(default=None, max_length=5)),
                ('status_of_terminal', models.CharField(default='not occupied', max_length=15)),
                ('date', models.DateField(default=None)),
                ('lock_time', models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 474965))),
                ('release_time', models.TimeField(default=datetime.datetime(2022, 3, 5, 13, 2, 19, 474965))),
                ('flight_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.airline_company')),
            ],
        ),
    ]
